defaults:
  - _self_
  - logging: colorlog
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  - override /hydra/launcher: ray_jobs

hydra:
  launcher:
    _target_: hydra_plugins.hydra_ray_jobs_launcher.ray_jobs_launcher.RayJobsLauncher
    poll_jobs: false
    entrypoint_num_gpus: 1
    enable_gpu_blocking: true
    entrypoint_resources:
      tensor-saes-scaling_strategies: 1

# Some default debug params
sae:
  checkpoint_dir: ./checkpoints/default
  seq_len: 128
  num_latents: 512
  model_name: EleutherAI/pythia-14m
  filtering_strategy: acc_features
  filtering_threshold: 1e-3

apply_to_all_tokens: false

test_size: 0.8
global_max_ds_size: 500
seed: 42
test_sequence_index: 0
marginalize_across_sequences: true

stats_batch_size: 512
causal_batch_size: 128
marginalization_batch_size: 64

debug: false
device: cuda
