defaults:
  - _self_
  - experiment: null
  - launcher: null
  - logging: colorlog

# Some default debug params
sae:
  checkpoint_dir: ./checkpoints/default
  seq_len: 128
  num_latents: 512
  model_name: EleutherAI/pythia-14m

test_size: 0.8
global_max_ds_size: 1000
seed: 42
test_sequence_index: 0

debug: false
device: cpu
