defaults:
  - _self_
  - override hydra/launcher: ray_jobs

hydra:
  launcher:
    poll_jobs: false

seed: 42
model: EleutherAI/pythia-70m
dataset: togethercomputer/RedPajama-Data-1T-Sample
split: train
train_split: train
train_test_split: 0.8
ds_name: null
ctx_len: 64
hf_token: null
load_in_8bit: false
max_train_examples: -1
max_test_examples: -1
data_preprocessing_num_proc: 48

# distributed
ddp: false
tp: false
port: 29500

optimizer: adam

sae:
  expansion_factor: 8
  normalize_decoder: true
  scale_encoder_k: false
  scale_encoder_fvu_batch: null
  scale_encoder_fvu_global: null
  num_latents: 0
  k: 128
  signed: false
  post_act_bias: false

batch_size: 8
grad_acc_steps: 1
micro_acc_steps: 1
lr: null
lr_warmup_steps: 1000
normalize_hiddens: true
auxk_alpha: 0.0
dead_feature_threshold: 10000000
enable_cross_layer_training: true
hookpoints: []
layers: []
layer_stride: 1
distribute_modules: false
save_every: 1000
root_path: checkpoints
log_to_wandb: true
stdout_log_frequency: 10
run_name: null
wandb_group: null
wandb_log_frequency: 1
